# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
platform :ios, "8.3"

target 'TodoApplication' do
    pod 'MagicalRecord'
end

target 'TodoApplicationTests' do

end

target 'TodoApplicationUITests' do

end

